### ISSUE TITLE
Add Error Handling to HTTPCONN

### ISSUE THREAD

**Issue by realAndrewCohn** [DanielSeehausen/fi-field-day#23]
https://github.com/DanielSeehausen/fi-field-day/blob/612fdf36da7d32ab8bf144ad8ab2c5bb275ba78c/code/browser-canvas-client/HTTPConn.js#L2

We should have some kind of fetch error handling here, especially if our rate limiting is going to send data back to the students

**Comment by DanielSeehausen** [comment]
we aren't rate limiting the browsers for the time being. if we need to let's sort that out later
