### ISSUE TITLE
Determine Which Endpoints the Nexus™️ Needs

### ISSUE THREAD

**Issue by realAndrewCohn** [DanielSeehausen/fi-field-day#31]
https://github.com/DanielSeehausen/fi-field-day/blob/f7241216f068ed7053ee47837896c069650a7f13/code/node-server/index.js#L29

Node Server will need to have several endpoints for the Nexus. Not sure what they are yet. Creating issue so we can continue to track this

**Comment by DanielSeehausen** [comment]
`setTile` and `getBoard` are the only endpoints nexus needs i think, unless someone thinks there are more required? Dimensions can be determined from getBoard size square rooted.
