### ISSUE TITLE
Dynamically Generate Identicons

### ISSUE THREAD

**Issue by realAndrewCohn** [DanielSeehausen/fi-field-day#4]
https://github.com/DanielSeehausen/fi-field-day/blob/089268975484764a1567bf43e9427ca7fb59b923/code/node-server/config.js#L1

This is lower on the priority list, but should we consider dynamically generating identicons?

**Comment by DanielSeehausen** [comment]
most def

**Comment by realAndrewCohn** [comment]
duplicate issue. Closing in favor of #26 

my bad
